version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: training_institute_frontend
    ports:
      - "3000:80"
    restart: unless-stopped
